# Dependencies
kramdown:
  input: GFM
  syntax_highlighter: rouge
# redcarpet:
#   extensions: ["strikethrough"]
# pygments:         true
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Travis Ingram
tagline:          'Beginner => Competent => Proficient'
url:              https://github.com/TravisIngram/travisingram.github.io
paginate:         3
paginate_path:    'page:num'
baseurl:          /
author:
  name:           'Travis Ingram'
  url:            https://twitter.com/td_ingram
  email:          ingramtravis@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           github.com/travisingram/travisingram.github.io

# Navigation
pages_list:
  About:          '/about'
  Archive:        '/archive'
  Feed:           '/atom.xml'

gems:             [jekyll-paginate]
